accounts/urls.py
from django.urls import path
from . import views
from posts.views import ProfileDetailView
from django.contrib.auth.views import LoginView
from .forms import LoginForm

app_name = 'accounts'
urlpatterns = [
    path('register/',views.RegisterView.as_view(),name="register"),
    path('login/',
         LoginView.as_view(template_name="accounts/auth/login.html",
                           authentication_form= LoginForm),
          name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='edit_profile'),
    path('profile/<str:username>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/<str:username>/about', views.ProfileAboutView.as_view(), name='profile-about'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('post/create', views.PostCreateView.as_view(), name="create_post"),


]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('posts/',include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from . import AccountsUtils


# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = PhoneNumberField(blank=True, null=True, unique=False)
    profile_photo = models.ImageField(upload_to=AccountsUtils.profile_image_path, blank=True, default='profile_pics/default.webp')
    cover_photo = models.ImageField(upload_to=AccountsUtils.cover_image_path, blank=True, default='cover_pics/default.webp')
    address = models.TextField(blank=True, null=True)

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from . import models
from phonenumber_field.formfields import PhoneNumberField



class RegisterionForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=30)
    last_name = forms.CharField(required=True, max_length=30)
    email = forms.EmailField(required=True, label="Email address")
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {
            'first_name': 'Enter first name',
            'last_name': 'Enter last name',
            'username': 'Enter username',
            'email': 'Enter email address',
            'password1': 'Enter password',
            'password2': 'Confirm Password',
        }
        for name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control mb-0',
                'placeholder': placeholders.get(name, '')
            })

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {
                'username': 'Enter username',
                'email': 'Enter your email address',
                'password': 'Enter password',
            }
        for name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control mb-0',
                'placeholder': placeholders.get(name, '')
            })


class ProfileForm(forms.ModelForm):
    phone_number = PhoneNumberField(required=False)
    class Meta():
        model = models.Profile
        fields = ['phone_number', 'profile_photo', 'address']
        widgets = {
            'phone_number': forms.TextInput(attrs={'class': 'form-control',
                'type': 'tel',
                'id': 'id_phone_number',
            }),
            'profile_photo': forms.FileInput(attrs={'class': 'file-upload','accept': 'image/*'}), 
            'address': forms.TextInput(attrs={'class': 'form-control'}), 
        }

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}), 
            'username': forms.TextInput(attrs={'class': 'form-control'}), 
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


        

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout, login
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic import DetailView, FormView, TemplateView, View, CreateView
from django.urls import reverse_lazy
from . import forms, models


class RegisterView(CreateView):
    template_name = "accounts/auth/register.html"
    model = User
    form_class = forms.RegisterionForm
    success_url = reverse_lazy('accounts:edit_profile')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

@require_POST
def logout_view(request):
    logout(request)
    return redirect('accounts:login')

class ProfileEditView(LoginRequiredMixin, View):
    template_name = "accounts/profile/edit.html"

    def get(self, request, *args, **kwargs):
        user_form = forms.UserForm(instance=request.user)
        profile_form = forms.ProfileForm(instance=request.user.profile)
        context = {'user_form': user_form, 'profile_form': profile_form}
        return render (request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        user_form = forms.UserForm(request.POST, instance=request.user)
        profile_form = forms.ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile', username=request.user.username)
        return render(request, self.template_name, {
            'user_form': user_form,
            'profile_form': profile_form
        })
    
class ProfileAboutView(DetailView):
    model = User
    template_name = "accounts/profile/about.html"
    slug_field = 'username'
    slug_url_kwarg = 'username'

accounts/templates/accounts/profile/profile-base.html
{% extends "layouts/base.html" %}
{% load static %}
{% block title %} Profile {% endblock  %}
{% block content %}
<div class="row">
      <div class="col-sm-12">
         <div class="card">
            <div class="card-body profile-page p-0">
               <div class="profile-header">
                  <div class="position-relative">
                     <img src="{% static "assets/images/page-img/profile-bg1.jpg" %}" alt="profile-bg" class="rounded img-fluid">
                     <ul class="header-nav list-inline d-flex flex-wrap justify-end p-0 m-0">
                        <li><a href="#"><i class="ri-pencil-line"></i></a></li>
                        <li><a href="#"><i class="ri-settings-4-line"></i></a></li>
                     </ul>
                  </div>
                  <div class="user-detail text-center mb-3">
                     <div class="profile-img">
                        <img src="{{ profile_user.profile.profile_photo.url }}" alt="profile-img" class="avatar-130 img-fluid" />
                     </div>
                     <div class="profile-detail">
                        <h3 class="">{{ profile_user.profile.full_name }}</h3>
                     </div>
                  </div>
                  <div class="profile-info p-3 d-flex align-items-center justify-content-between position-relative">
                     <div class="social-links">
                        <ul class="social-data-block d-flex align-items-center justify-content-between list-inline p-0 m-0">
                           <li class="text-center pe-3">
                              <a href="#"><img src="{% static "assets/images/icon/08.png" %}" class="img-fluid rounded" alt="facebook"></a>
                           </li>
                           <li class="text-center pe-3">
                              <a href="#"><img src="{% static 'assets/images/icon/09.png' %}" class="img-fluid rounded" alt="Twitter"></a>
                           </li>
                           <li class="text-center pe-3">
                              <a href="#"><img src="{% static 'assets/images/icon/10.png' %}" class="img-fluid rounded" alt="Instagram"></a>
                           </li>
                           <li class="text-center pe-3">
                              <a href="#"><img src="{% static 'assets/images/icon/11.png' %}" class="img-fluid rounded" alt="Google plus"></a>
                           </li>
                           <li class="text-center pe-3">
                              <a href="#"><img src="{% static 'assets/images/icon/12.png' %}" class="img-fluid rounded" alt="You tube"></a>
                           </li>
                           <li class="text-center md-pe-3 pe-0">
                              <a href="#"><img src="{% static 'assets/images/icon/13.png' %}" class="img-fluid rounded" alt="linkedin"></a>
                           </li>
                        </ul>
                     </div>
                     <div class="social-info">
                        <ul class="social-data-block d-flex align-items-center justify-content-between list-inline p-0 m-0">
                           <li class="text-center ps-3">
                              <h6>Posts</h6>
                              <p class="mb-0">690</p>
                           </li>
                           <li class="text-center ps-3">
                              <h6>Followers</h6>
                              <p class="mb-0">206</p>
                           </li>
                           <li class="text-center ps-3">
                              <h6>Following</h6>
                              <p class="mb-0">100</p>
                           </li>
                        </ul>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="card">
            <div class="card-body p-0">
               <div class="user-tabing">
                  <ul class="nav nav-pills d-flex align-items-center justify-content-center profile-feed-items p-0 m-0">
                     <li class="nav-item col-12 col-sm-3 p-0">
                        <a class="nav-link {% if request.resolver_match.url_name == 'profile' %}active{% endif %}" href="{% url "accounts:profile" user.username %}"  >Timeline</a>
                     </li>
                     <li class="nav-item col-12 col-sm-3 p-0">
                        <a class="nav-link {% if request.resolver_match.url_name == 'profile-about' %}active{% endif %}" href="{% url "accounts:profile-about" user.username %}">About</a>
                     </li>
                     <li class="nav-item col-12 col-sm-3 p-0">
                        <a class="nav-link" href="#pills-friends-tab" data-bs-toggle="pill" data-bs-target="#friends" role="button">Friends</a>
                     </li>
                     <li class="nav-item col-12 col-sm-3 p-0">
                        <a class="nav-link" href="#pills-photos-tab" data-bs-toggle="pill" data-bs-target="#photos" role="button">Photos</a>
                     </li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
         {% block ProfileContent %}{% endblock  %}
      <div class="col-sm-12 text-center">
         <img src="{% static "assets/images/page-img/page-load-loader.gif" %}" alt="loader" style="height: 100px;">
      </div>
   </div>
{% endblock  %}

accounts/templates/accounts/profile/timeline.html
{% extends "accounts/profile/profile-base.html" %}
{% load static %}
{% block ProfileContent %}
      <div class="col-sm-12">
         <div class="tab-content">
            <div class="tab-pane fade show active" id="timeline" role="tabpanel">
               <div class="card-body p-0">
                  <div class="row">
                     <div class="col-lg-4">
                        <div class="card">
                           <div class="card-body">
                              <a href="#"><span class="badge badge-pill bg-primary font-weight-normal ms-auto me-1"><i class="ri-star-line"></i></span> 27 Items for yoou</a>
                           </div>
                        </div>
                        <div class="card">
                           <div class="card-header d-flex justify-content-between">
                              <div class="header-title">
                                 <h4 class="card-title">Life Event</h4>
                              </div>
                              <div class="card-header-toolbar d-flex align-items-center">
                                 <p class="m-0"><a href="javacsript:void();"> Create </a></p>
                              </div>
                           </div>
                           <div class="card-body">
                              <div class="row">
                                 <div class="col-sm-12">
                                    <div class="event-post position-relative">
                                       <a href="#"><img src="{% static "assets/images/page-img/07.jpg" %}" alt="gallary-image" class="img-fluid rounded"></a>
                                       <div class="job-icon-position">
                                          <div class="job-icon bg-primary p-2 d-inline-block rounded-circle"><i class="ri-briefcase-line text-white"></i></div>
                                       </div>
                                       <div class="card-body text-center p-2">
                                          <h5>Started New Job at Apple</h5>
                                          <p>January 24, 2019</p>
                                       </div>
                                    </div>
                                 </div>
                                 <div class="col-sm-12">
                                    <div class="event-post position-relative">
                                       <a href="#"><img src="{% static 'assets/images/page-img/06.jpg' %}" alt="gallary-image" class="img-fluid rounded"></a>
                                       <div class="job-icon-position">
                                          <div class="job-icon bg-primary p-2 d-inline-block rounded-circle"><i class="ri-briefcase-line text-white"></i></div>
                                       </div>
                                       <div class="card-body text-center p-2">
                                          <h5>Freelance Photographer</h5>
                                          <p class="mb-0">January 24, 2019</p>
                                       </div>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                        <div class="card">
                           <div class="card-header d-flex justify-content-between">
                              <div class="header-title">
                                 <h4 class="card-title">Photos</h4>
                              </div>
                              <div class="card-header-toolbar d-flex align-items-center">
                                 <p class="m-0"><a href="javacsript:void();">Add Photo </a></p>
                              </div>
                           </div>
                           <div class="card-body">
                              <ul class="profile-img-gallary p-0 m-0 list-unstyled">
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g1.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g2.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g3.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g4.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g5.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g6.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g7.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g8.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                                 <li class=""><a href="#"><img src="{% static 'assets/images/page-img/g9.jpg' %}" alt="gallary-image" class="img-fluid" /></a></li>
                              </ul>
                           </div>
                        </div>
                        <div class="card">
                           <div class="card-header d-flex justify-content-between">
                              <div class="header-title">
                                 <h4 class="card-title">Friends</h4>
                              </div>
                              <div class="card-header-toolbar d-flex align-items-center">
                                 <p class="m-0"><a href="javacsript:void();">Add New </a></p>
                              </div>
                           </div>
                           <div class="card-body">
                              <ul class="profile-img-gallary p-0 m-0 list-unstyled">
                                 <li class="">
                                    <a href="#">
                                    <img src="{% static 'assets/images/user/05.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Anna Rexia</h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/06.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Tara Zona</h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/07.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Polly Tech</h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/08.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Bill Emia</h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/09.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Moe Fugga</h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/10.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Hal Appeno </h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/07.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Zack Lee</h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/06.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Terry Aki</h6>
                                 </li>
                                 <li class="">
                                    <a href="#"><img src="{% static 'assets/images/user/05.jpg' %}" alt="gallary-image" class="img-fluid" /></a>
                                    <h6 class="mt-2 text-center">Greta Life</h6>
                                 </li>
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-8">
                        {% if request.user.is_authenticated and request.user == profile_user  %}
                        <div id="post-modal-data" class="card">
                           <div class="card-header d-flex justify-content-between">
                              <div class="header-title">
                                 <h4 class="card-title">Create Post</h4>
                              </div>
                           </div>
                           <div class="card-body">
                              <div class="d-flex align-items-center">
                                 <div class="user-img">
                                    <img src="{% static "assets/images/user/1.jpg" %}" alt="userimg" class="avatar-60 rounded-circle">
                                 </div>
                                 <form class="post-text ms-3 w-100 "  data-bs-toggle="modal" data-bs-target="#post-modal" method="POST">
                                    <input type="text" class="form-control rounded" placeholder="Write something here..." style="border:none;">

                                 </form>
                              </div>
                              <hr>
                               <ul class=" post-opt-block d-flex list-inline m-0 p-0 flex-wrap">
                                    <li class="bg-soft-primary rounded p-2 pointer d-flex align-items-center me-3 mb-md-0 mb-2"><img src="{% static "assets/images/small/07.png" %}" alt="icon" class="img-fluid me-2"> Photo/Video</li>
                                    <li class="bg-soft-primary rounded p-2 pointer d-flex align-items-center me-3 mb-md-0 mb-2"><img src="{% static "assets/images/small/08.png" %}" alt="icon" class="img-fluid me-2"> Tag Friend</li>
                                    <li class="bg-soft-primary rounded p-2 pointer d-flex align-items-center me-3"><img src="{% static "assets/images/small/09.png" %}" alt="icon" class="img-fluid me-2"> Feeling/Activity</li>
                                    <li class="bg-soft-primary rounded p-2 pointer text-center">
                                        <div class="card-header-toolbar d-flex align-items-center">
                                        <div class="dropdown">
                                            <div class="dropdown-toggle" id="post-option"   data-bs-toggle="dropdown">
                                                <i class="ri-more-fill h4"></i>
                                            </div>
                                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="post-option" style="">
                                                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#post-modal">Check in</a>
                                                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#post-modal">Live Video</a>
                                                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#post-modal">Gif</a>
                                                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#post-modal">Watch Party</a>
                                                <a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#post-modal">Play with Friend</a>
                                            </div>
                                        </div>
                                        </div>
                                    </li>
                                </ul>
                           </div>
                           {% include "accounts/components/_post-modal.html" %}
                       </div>
                       {% endif %}

                       <div class="card" id="post-list">
                        {% for post in posts  %}
                           {% include "accounts/components/_post.html" %}
                        {% empty %}
                           <h1 class="text-center"> No Posts Available </h1>
                        {% endfor %}
                        
                        </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <script>
function closeModalAndResetForm(form) {
    let modal = bootstrap.Modal.getInstance(document.getElementById('post-modal'));
    if (modal) {
        modal.hide();
    }
    form.reset();
}
</script>

{% endblock  %}