accounts/urls.py
from django.urls import path
from . import views
from posts.views import ProfileDetailView
from django.contrib.auth.views import LoginView
from .forms import LoginForm

app_name = 'accounts'
urlpatterns = [
    path('register/',views.RegisterView.as_view(),name="register"),
    path('login/',
         LoginView.as_view(template_name="accounts/auth/login.html",
                           authentication_form= LoginForm),
          name="login"),
    path('logout/', views.logout_view, name='logout'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='edit_profile'),
    path('profile/<str:username>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/<str:username>/about', views.ProfileAboutView.as_view(), name='profile-about'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('post/create', views.PostCreateView.as_view(), name="create_post"),


]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('posts/',include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from . import AccountsUtils


# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = PhoneNumberField(blank=True, null=True, unique=False)
    profile_photo = models.ImageField(upload_to=AccountsUtils.profile_image_path, blank=True, default='profile_pics/default.webp')
    cover_photo = models.ImageField(upload_to=AccountsUtils.cover_image_path, blank=True, default='cover_pics/default.webp')
    address = models.TextField(blank=True, null=True)

    @property
    def full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from socialmedia import SharedUtils
from PIL import Image as PILImage

# Create your models here.

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        indexes = [
            models.Index(fields=["user", "-created_at"]),
        ]

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=SharedUtils.post_image_path)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
    # Save image first to get path
        super().save(*args, **kwargs)

        # Open the image file
        img_path = self.image.path
        img = PILImage.open(img_path)

        # Force resize to fixed width & height
        target_size = (621, 400)  # width, height in px
        img = img.resize(target_size, PILImage.LANCZOS)

        # Save optimized
        img.save(img_path, optimize=True, quality=85)

    
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from . import models
from phonenumber_field.formfields import PhoneNumberField



class RegisterionForm(UserCreationForm):
    first_name = forms.CharField(required=True, max_length=30)
    last_name = forms.CharField(required=True, max_length=30)
    email = forms.EmailField(required=True, label="Email address")
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {
            'first_name': 'Enter first name',
            'last_name': 'Enter last name',
            'username': 'Enter username',
            'email': 'Enter email address',
            'password1': 'Enter password',
            'password2': 'Confirm Password',
        }
        for name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control mb-0',
                'placeholder': placeholders.get(name, '')
            })

class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {
                'username': 'Enter username',
                'email': 'Enter your email address',
                'password': 'Enter password',
            }
        for name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'form-control mb-0',
                'placeholder': placeholders.get(name, '')
            })


class ProfileForm(forms.ModelForm):
    phone_number = PhoneNumberField(required=False)
    class Meta():
        model = models.Profile
        fields = ['phone_number', 'profile_photo', 'address']
        widgets = {
            'phone_number': forms.TextInput(attrs={'class': 'form-control',
                'type': 'tel',
                'id': 'id_phone_number',
            }),
            'profile_photo': forms.FileInput(attrs={'class': 'file-upload','accept': 'image/*'}), 
            'address': forms.TextInput(attrs={'class': 'form-control'}), 
        }

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}), 
            'username': forms.TextInput(attrs={'class': 'form-control'}), 
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


        

posts/forms.py
from django import forms
from django.forms import inlineformset_factory
from . import models
from django.forms.widgets import ClearableFileInput



class MultipleFileInput(ClearableFileInput):
    allow_multiple_selected = True


class PostForm(forms.ModelForm):
    
    class Meta:
        model = models.Post
        fields = ("content",)
        widgets = {
            "content": forms.TextInput(attrs={'class':'form-control rounded'})
        }


class ImageForm(forms.ModelForm):
    image = forms.ImageField(
        widget=MultipleFileInput(attrs={'multiple': True}),
        required=False
    )

    class Meta:
        model = models.Image
        fields = ['image']


ImageFormSet = inlineformset_factory(models.Post, 
                                    models.Image,
                                    form=ImageForm, 
                                    extra=1,
                                    can_delete=False)

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout, login
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic import DetailView, FormView, TemplateView, View, CreateView
from django.urls import reverse_lazy
from . import forms, models


class RegisterView(CreateView):
    template_name = "accounts/auth/register.html"
    model = User
    form_class = forms.RegisterionForm
    success_url = reverse_lazy('accounts:edit_profile')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

@require_POST
def logout_view(request):
    logout(request)
    return redirect('accounts:login')

class ProfileEditView(LoginRequiredMixin, View):
    template_name = "accounts/profile/edit.html"

    def get(self, request, *args, **kwargs):
        user_form = forms.UserForm(instance=request.user)
        profile_form = forms.ProfileForm(instance=request.user.profile)
        context = {'user_form': user_form, 'profile_form': profile_form}
        return render (request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        user_form = forms.UserForm(request.POST, instance=request.user)
        profile_form = forms.ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile', username=request.user.username)
        return render(request, self.template_name, {
            'user_form': user_form,
            'profile_form': profile_form
        })
    
class ProfileAboutView(DetailView):
    model = User
    template_name = "accounts/profile/about.html"
    slug_field = 'username'
    slug_url_kwarg = 'username'

posts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import forms
from . import models
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.shortcuts import redirect

# Create your views here.


class PostCreateView(LoginRequiredMixin, CreateView):
    model = models.Post
    form_class = forms.PostForm
    
    def form_valid(self, form):
        form.instance.user = self.request.user  
        self.object = form.save()
        for uploaded_file in self.request.FILES.getlist('images-0-image'):
            models.Image.objects.create(post=self.object, image=uploaded_file)
        return render(self.request, "accounts/components/_post.html", {"post": self.object})

    

class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "accounts/profile/timeline.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    
    def get_queryset(self):
        # Fetch the user + profile in one query
        return (
            super()
            .get_queryset()
            .select_related("profile")  # join with profile
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profile_user = self.object

        # Fetch posts + images + author's profile in one query per table
        posts = (
            models.Post.objects.filter(user=profile_user)
            .order_by("-created_at")
            .select_related("user",)  # author + author profile
            .prefetch_related("images")  # all images in one query
        )

        context.update({
            "profile_user": profile_user,
            "posts": posts,
            "form": forms.PostForm(),
            "formset": forms.ImageFormSet(),
        })
        return context

accounts/templates/accounts/components/_post-modal.html
{% load static %}
<div class="modal fade" id="post-modal" tabindex="-1"  aria-labelledby="post-modalLabel" aria-hidden="true" >
                              <div class="modal-dialog  modal-lg modal-fullscreen-sm-down">
                                 <div class="modal-content">
                                    <div class="modal-header">
                                       <h5 class="modal-title" id="post-modalLabel">Create Post</h5>
                                       <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="ri-close-fill"></i></button>
                                    </div>
                                    <div class="modal-body">
                                       <div class="d-flex align-items-center">
                                          <div class="user-img">
                                             <img src="{% static "assets/images/user/1.jpg" %}" alt="userimg" class="avatar-60 rounded-circle img-fluid">
                                          </div>
                                          <form class="post-text ms-3 w-100"
                                                enctype="multipart/form-data"
                                                hx-post="{% url 'posts:create_post' %}"
                                                hx-target="#post-list"
                                                hx-swap="afterbegin"
                                                hx-on::after-request="closeModalAndResetForm(this)">
                                             {% csrf_token %}
                                             {{ form.content }}
                                             <h4>Images</h4>
                                             {{ formset.management_form }}
                                             {% for img_form in formset %}
                                                {{ img_form.as_p }}
                                             {% endfor %}
                                             <button type="submit" class="btn btn-primary d-block w-100 mt-3">Post</button>
                                          </form>
                                       </div>
                                       <hr>
                                       <ul class="d-flex flex-wrap align-items-center list-inline m-0 p-0">
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="../assets/images/small/07.png" alt="icon" class="img-fluid"> Photo/Video</div>
                                          </li>
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="../assets/images/small/08.png" alt="icon" class="img-fluid"> Tag Friend</div>
                                          </li>
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="../assets/images/small/09.png" alt="icon" class="img-fluid"> Feeling/Activity</div>
                                          </li>
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="{% static "assets/images/small/10.png" %}" alt="icon" class="img-fluid"> Check in</div>
                                          </li>
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="{% static "assets/images/small/11.png" %}" alt="icon" class="img-fluid"> Live Video</div>
                                          </li>
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="{% static "assets/images/small/12.png" %}" alt="icon" class="img-fluid"> Gif</div>
                                          </li>
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="{% static "assets/images/small/13.png" %}" alt="icon" class="img-fluid"> Watch Party</div>
                                          </li>
                                          <li class="col-md-6 mb-3">
                                             <div class="bg-soft-primary rounded p-2 pointer me-3"><a href="#"></a><img src="{% static "assets/images/small/14.png" %}" alt="icon" class="img-fluid"> Play with Friends</div>
                                          </li>
                                       </ul>
                                       <hr>
                                       <div class="other-option">
                                          <div class="d-flex align-items-center justify-content-between">
                                             <div class="d-flex align-items-center">
                                                <div class="user-img me-3">
                                                   <img src="{% static "assets/images/user/1.jpg" %}" alt="userimg" class="avatar-60 rounded-circle img-fluid">
                                                </div>
                                                <h6>Your Story</h6>
                                             </div>
                                             <div class="card-post-toolbar">
                                                <div class="dropdown">
                                                   <span class="dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" role="button">
                                                   <span class="btn btn-primary">Friend</span>
                                                   </span>
                                                   <div class="dropdown-menu m-0 p-0">
                                                      <a class="dropdown-item p-3" href="#">
                                                         <div class="d-flex align-items-top">
                                                            <i class="ri-save-line h4"></i>
                                                            <div class="data ms-2">
                                                               <h6>Public</h6>
                                                               <p class="mb-0">Anyone on or off Facebook</p>
                                                            </div>
                                                         </div>
                                                      </a>
                                                      <a class="dropdown-item p-3" href="#">
                                                         <div class="d-flex align-items-top">
                                                           <i class="ri-close-circle-line h4"></i>
                                                            <div class="data ms-2">
                                                               <h6>Friends</h6>
                                                               <p class="mb-0">Your Friend on facebook</p>
                                                            </div>
                                                         </div>
                                                      </a>
                                                      <a class="dropdown-item p-3" href="#">
                                                         <div class="d-flex align-items-top">
                                                           <i class="ri-user-unfollow-line h4"></i>
                                                            <div class="data ms-2">
                                                               <h6>Friends except</h6>
                                                               <p class="mb-0">Don't show to some friends</p>
                                                            </div>
                                                         </div>
                                                      </a>
                                                      <a class="dropdown-item p-3" href="#">
                                                         <div class="d-flex align-items-top">
                                                           <i class="ri-notification-line h4"></i>
                                                            <div class="data ms-2">
                                                               <h6>Only Me</h6>
                                                               <p class="mb-0">Only me</p>
                                                            </div>
                                                         </div>
                                                      </a>
                                                   </div>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                       
                                    </div>
                                 </div>
                              </div>
                           </div>